'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

const MRT_Localization_AR = {
    actions: 'عملیات',
    and: 'و',
    cancel: 'انصراف',
    changeFilterMode: 'تغییر حالت فیلتر',
    changeSearchMode: 'تغییر حالت جستجو',
    clearFilter: 'مسح البحث',
    clearSearch: 'مسح منقي',
    clearSort: 'مسح فرز',
    clickToCopy: 'کپی کردن',
    columnActions: 'اقدامات ستون',
    copiedToClipboard: 'کپی به کلیپ بورد',
    dropToGroupBy: 'حذف گروه بندی {column}',
    edit: 'ویرایش',
    expand: 'باز کردن',
    expandAll: 'باز کردن همه',
    filterArrIncludes: 'شامل',
    filterArrIncludesAll: 'شامل همه',
    filterArrIncludesSome: 'شامل برخی',
    filterBetween: 'بین',
    filterBetweenInclusive: 'شامل بین',
    filterByColumn: 'مصنف بواسطة {column}',
    filterContains: 'شامل',
    filterEmpty: 'خالی',
    filterEndsWith: 'به پایان می رسد با',
    filterEquals: 'مساوی',
    filterEqualsString: 'مساوی',
    filterFuzzy: 'درهم',
    filterGreaterThan: 'بزرگتر از',
    filterGreaterThanOrEqualTo: 'بزرگتر مساوی با',
    filterInNumberRange: 'بین',
    filterIncludesString: 'شامل',
    filterIncludesStringSensitive: 'شامل',
    filterLessThan: 'کمتر از',
    filterLessThanOrEqualTo: 'کمتر مساوی با',
    filterMode: ' فیلتر :{filterType}',
    filterNotEmpty: 'خالی نبودن  ',
    filterNotEquals: 'مساوی نبودن با  ',
    filterStartsWith: 'شروع با ',
    filterWeakEquals: 'مساوی با ',
    filteringByColumn: 'فیلتر با {column} - {filtertype} {filtervalue}',
    goToFirstPage: 'صفحه اول',
    goToLastPage: 'صفحه آخر',
    goToNextPage: 'صفحه بعد',
    goToPreviousPage: 'صفحه قبل',
    grab: 'گرفتن',
    groupByColumn: 'گروه بندی توسط {column}',
    groupedBy: 'گروه بندی توسط ',
    hideAll: 'أخف كل شيء',
    hideColumn: '{column} إخفاء العمود',
    max: 'حداکثر',
    min: 'حداقل',
    move: 'حرکت',
    noRecordsToDisplay: 'لا سجلات لعرضها',
    noResultsFound: 'موردی یافت نشد.',
    of: 'من',
    or: 'أو',
    pinToLeft: 'پین به چپ',
    pinToRight: 'پین به راست',
    resetColumnSize: 'تنظیم مجدد اندازه ستون',
    resetOrder: 'بازنشانی سفارش',
    rowActions: 'اقدامات ردیف',
    rowNumber: '#',
    rowNumbers: 'اعداد ردیف',
    rowsPerPage: 'عدد الصفوف في الصفحة',
    save: 'ذخیره کردن',
    search: 'يبحث',
    selectedCountOfRowCountRowsSelected: '{selectedCount} از {rowCount} انتخاب شد',
    select: 'انتخاب',
    showAll: 'عرض الكل',
    showAllColumns: 'إظهار كافة الأعمدة',
    showHideColumns: 'إظهار / إخفاء الأعمدة',
    showHideFilters: 'إظهار / إخفاء المرشحات',
    showHideSearch: 'إظهار / إخفاء البحث',
    sortByColumnAsc: '{column} فرز حسب  تصاعديًا',
    sortByColumnDesc: '{column} فرز حسب تنازلي',
    sortedByColumnAsc: 'تصاعديًا {column} مرتبة حسب',
    sortedByColumnDesc: 'تنازلي {column} مرتبة حسب',
    thenBy: 'سپس توسط ',
    toggleDensity: 'تبديل الكثافة',
    toggleFullScreen: 'ملء الشاشة تبديل',
    toggleSelectAll: 'انتخاب همه',
    toggleSelectRow: 'انتخاب ردیف',
    toggleVisibility: 'نمایش',
    ungroupByColumn: 'لغو گروه بندی توسط {column}',
    unpin: 'پین کردن',
    unpinAll: 'از پین در آوردن ',
    unsorted: '  مرتب نشده ',
};

exports.MRT_Localization_AR = MRT_Localization_AR;
//# sourceMappingURL=fa.js.map
